/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/commodities/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a commodity data import from the UEX feed.
         * @description Fetches the full UEX commodities feed server-side and performs a transactional upsert: inserts new
         *     commodities, updates existing ones, reactivates previously soft-deleted commodities that reappear
         *     (FR-007), and soft-deletes commodities absent from the feed (FR-006). Records missing `id` or `name`
         *     are skipped and counted (FR-005). Integer flags are normalized to booleans, comma-separated location
         *     ids are parsed to integer arrays, and Unix timestamps are converted to UTC, all stored alongside the
         *     verbatim source object (FR-008..FR-013). Pricing fields are never imported (FR-014). Any source
         *     failure rolls back / applies nothing (SC-007). Only one import may run at a time (FR-016).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Import completed; counts of what changed (FR-017). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCommoditiesResult"];
                    };
                };
                /**
                 * @description Feed returned zero records — no commodities inserted/updated; any previously active commodities
                 *     are soft-deleted. Body carries a warning message and the counts.
                 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCommoditiesResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description An import or refresh is already in progress (FR-016). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /**
                 * @description The external UEX feed was unavailable or returned an unusable/invalid-shape response (FR-003);
                 *     no changes applied (SC-007).
                 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/commodities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List imported commodities (paged), for verifying import results.
         * @description Read-only, admin-only paged listing of imported commodities (active and soft-deleted). Returns a
         *     lightweight projection per row; the verbatim source object (`raw_data`) is not included.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page number. Values below 1 are treated as 1. */
                    page?: number;
                    /** @description Page size, clamped to 1..100. */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of commodities. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedCommoditiesResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImportCommoditiesResult: {
            /** @description Records returned by the source feed. */
            fetched: number;
            /** @description Records skipped for missing id or name (FR-005). */
            skipped: number;
            /** @description New commodities inserted this run. */
            inserted: number;
            /** @description Existing active commodities whose promoted fields changed this run. */
            updated: number;
            /** @description Existing active commodities present but unchanged this run. */
            unchanged: number;
            /** @description Previously soft-deleted commodities reactivated (FR-007). */
            restored: number;
            /** @description Commodities absent from the feed */
            softDeleted: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** @description Wall-clock import duration in milliseconds. */
            durationMs: number;
            /** @description Set when the feed returned zero records. */
            warning?: string | null;
        };
        CommodityListItem: {
            /** Format: uuid */
            id: string;
            /** @description UEX source identity (uex_id). */
            uexId: number;
            name: string;
            code?: string | null;
            kind?: string | null;
            /** @enum {string} */
            status: "active" | "softDeleted";
        };
        PagedCommoditiesResult: {
            items: components["schemas"]["CommodityListItem"][];
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
        /** @description RFC 7807 problem document (as emitted by the API's ProblemDetails middleware). */
        ProblemDetails: {
            title?: string;
            status?: number;
            detail?: string | null;
            instance?: string | null;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacking the Admin role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
