/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hangar/mine/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the current member's hangar from a HangarXPLOR JSON export
         * @description Atomically removes all of the current member's hangar entries and inserts one entry per distinct Active catalog ship whose name matches a non-"unidentified" import record. An empty items array clears the hangar. Returns a summary of imported and skipped records.
         */
        post: operations["importHangar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One element of the HangarXPLOR export array. Extra/unknown fields (ship_code, manufacturer_code, manufacturer_name, lti, warbond, entity_type, pledge_*, lookup, …) are accepted and ignored. The effective match key is shipName when non-blank, else name. */
        ImportShipRecord: {
            /**
             * @description Display/fallback name; present on every export record.
             * @example F8C Lightning
             */
            name: string;
            /**
             * @description The export's ship_name field. Preferred match key when present and non-blank.
             * @example F8C Lightning
             */
            shipName?: string | null;
            /** @description Present only on records the export tool could not identify. When present, the record is skipped before matching and counted as unmatched. */
            unidentified?: string | null;
        } & {
            [key: string]: unknown;
        };
        ImportHangarRequest: {
            /** @description The parsed export array. May be empty (clears the hangar). */
            items: components["schemas"]["ImportShipRecord"][];
        };
        ImportHangarResult: {
            /**
             * @description Number of records received in items.
             * @example 39
             */
            totalRecords: number;
            /**
             * @description Distinct Active catalog ships matched and now in the hangar (final size).
             * @example 36
             */
            importedShips: number;
            /**
             * @description Records skipped because they were "unidentified" or matched no Active catalog ship.
             * @example 3
             */
            unmatchedRecords: number;
            /**
             * @description Distinct effective names that did not match, for user display.
             * @example [
             *       "A.T.L.S.",
             *       "Some Unknown Ship"
             *     ]
             */
            unmatchedShipNames: string[];
        };
        /** @description RFC 7807 problem details. */
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    importHangar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportHangarRequest"];
            };
        };
        responses: {
            /** @description Import completed; returns a summary of the outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportHangarResult"];
                };
            };
            /** @description Malformed request body (missing/invalid items array or record shape). The hangar is left unchanged. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
