/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hangar/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current member's hangar (My Hangar) */
        get: operations["getMyHangar"];
        put?: never;
        /** Add a catalog ship to the current member's hangar */
        post: operations["addShipToHangar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hangar/mine/{shipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a ship from the current member's hangar */
        delete: operations["removeShipFromHangar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hangar/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the organization's aggregated hangar (Org Hangar)
         * @description Derived view: all members' HangarEntry rows grouped by unique ship model, each with an owner count and the list of owners. Supports name search, a "my ships" filter, and a single-member filter (memberId). Selecting memberId takes precedence over mine.
         */
        get: operations["getOrgHangar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hangar/org/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members who own at least one ship (for the member filter) */
        get: operations["getOwningMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hangar/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the ship catalog (sc.ships) by name for the Add Ship dialog
         * @description Searches active catalog ships by name (case-insensitive, partial). Each result is flagged alreadyOwned for the current member so the dialog can disable already-owned ships.
         */
        get: operations["searchCatalogShips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HangarShipCard: {
            /**
             * Format: uuid
             * @description sc.ships.id
             */
            shipId: string;
            /** @description sc.ships.name (card title */
            name: string;
            /** @description sc.ships.company_name */
            companyName?: string | null;
            /** @description raw_data->>'url_photo'; null/empty => default card background. */
            urlPhoto?: string | null;
            /** @description raw_data->>'scu' (cargo capacity), cast numeric; null when absent. */
            scu?: number | null;
            /** @description raw_data->>'crew' (crew size), kept as the stored string. */
            crew?: string | null;
        };
        OrgHangarShipCard: components["schemas"]["HangarShipCard"] & {
            /** @description Number of unique members who own this ship model. */
            ownerCount: number;
            /** @description Members who own this ship (drives the hover owner list). */
            owners: components["schemas"]["HangarOwner"][];
        };
        HangarOwner: {
            /** Format: uuid */
            userId: string;
            displayName: string;
        };
        CatalogSearchItem: components["schemas"]["HangarShipCard"] & {
            /** @description True when the current member already owns this ship (disable Add). */
            alreadyOwned: boolean;
        };
        OwningMember: {
            /** Format: uuid */
            userId: string;
            displayName: string;
        };
        AddShipRequest: {
            /**
             * Format: uuid
             * @description Catalog ship id (sc.ships.id) to add to the member's hangar.
             */
            shipId: string;
        };
        PagedHangarShipCards: {
            items: components["schemas"]["HangarShipCard"][];
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
        PagedOrgHangarShipCards: {
            items: components["schemas"]["OrgHangarShipCard"][];
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
        PagedCatalogSearchItems: {
            items: components["schemas"]["CatalogSearchItem"][];
            page: number;
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Case-insensitive, partial match against sc.ships.name. */
        Search: string;
        /** @description 1-based page index (infinite scroll advances pages). */
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyHangar: {
        parameters: {
            query?: {
                /** @description Case-insensitive, partial match against sc.ships.name. */
                search?: components["parameters"]["Search"];
                /** @description 1-based page index (infinite scroll advances pages). */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of the current member's ship cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedHangarShipCards"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addShipToHangar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddShipRequest"];
            };
        };
        responses: {
            /** @description Ship added; returns the created card. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HangarShipCard"];
                };
            };
            /** @description Validation error (missing/invalid shipId). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Catalog ship not found or not active. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Ship already in the member's hangar (duplicate ownership). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    removeShipFromHangar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Catalog ship id (sc.ships.id) to remove from the member's hangar. */
                shipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ship removed (idempotent if it was not present). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Removal failed; the ship remains in the member's hangar. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getOrgHangar: {
        parameters: {
            query?: {
                /** @description Case-insensitive, partial match against sc.ships.name. */
                search?: components["parameters"]["Search"];
                /** @description Limit to ships owned by the current member (My Ships filter). */
                mine?: boolean;
                /** @description Limit to ships owned by the given member. Overrides mine when present. */
                memberId?: string;
                /** @description 1-based page index (infinite scroll advances pages). */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of grouped org ship cards with owners. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedOrgHangarShipCards"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOwningMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members owning one or more ships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwningMember"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchCatalogShips: {
        parameters: {
            query?: {
                /** @description Case-insensitive, partial match against sc.ships.name. */
                search?: components["parameters"]["Search"];
                /** @description 1-based page index (infinite scroll advances pages). */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged catalog search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedCatalogSearchItems"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
