/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/items/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locally stored categories for the selector.
         * @description Returns all locally stored categories with the context the selector needs (section, name, type,
         *     game-related and mining-related flags, source modified date, and local import state) plus the
         *     page-level "categories last refreshed" aggregate. The SPA filters/searches client-side
         *     (search, section, mining-related, game-related). Only `type = "item"` rows expose import actions.
         *     When no categories exist, `items` is empty and `lastRefreshedAt` is null — the SPA disables import
         *     actions and explains that categories must be refreshed first.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local categories (possibly empty) plus the last-refreshed aggregate. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/items/categories/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh categories from the UEX categories endpoint.
         * @description Fetches the full UEX categories feed server-side and upserts into local storage by source id.
         *     Atomic with respect to failure: if the fetch or response shape is invalid, no partial category
         *     data is stored. Separate from item import; this is the only operation that calls the UEX
         *     categories endpoint. Only one import or refresh may run at a time.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Refresh completed; category-refresh summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshCategoriesResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description An import or refresh is already in progress. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The UEX categories endpoint was unavailable or returned an unusable response; no changes applied. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/items/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import items for one category or for all eligible categories.
         * @description Imports items using locally stored categories only — never calls the UEX categories endpoint.
         *     If `categoryUexId` is provided, imports that single category (must be `type = "item"`). If omitted
         *     or null, imports all eligible (`type = "item"`) local categories sequentially; a failure in one
         *     category is recorded and the run continues with the remaining categories. For each category:
         *     fetches `GET /items?id_category={id}`, upserts items by `uuid` (insert new, update existing,
         *     restore previously soft-deleted that reappear), skips and counts `uuid = null` records, and
         *     soft-deletes — scoped to that category only — items absent from the response. Returns an aggregate
         *     summary with per-category error details. Only one import or refresh may run at a time. Requires at
         *     least one local category to exist.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ImportItemsRequest"];
                };
            };
            responses: {
                /**
                 * @description Import finished. `status` is `success` (all categories succeeded), `completedWithErrors`
                 *     (some categories failed; see `errors`), or `failed` (all categories failed).
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportItemsResult"];
                    };
                };
                /**
                 * @description No local categories exist, the requested category id is unknown, or it is not eligible
                 *     (`type != "item"`).
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description An import or refresh is already in progress. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CategoryListItem: {
            /** @description UEX source id (route id). */
            uexId: number;
            /** @example Weapons */
            name: string;
            /** @example Personal */
            section?: string | null;
            /**
             * @description Only "item" categories are import-eligible.
             * @example item
             */
            type: string;
            isGameRelated: boolean;
            isMining: boolean;
            /**
             * Format: date-time
             * @description UEX date_modified for the category.
             */
            sourceDateModified?: string | null;
            /** @description Count of non-soft-deleted items currently stored locally for this category. */
            localItemCount?: number;
            /**
             * Format: date-time
             * @description When items for this category were last imported, if ever.
             */
            lastImportedAt?: string | null;
        };
        CategoryList: {
            items: components["schemas"]["CategoryListItem"][];
            /**
             * Format: date-time
             * @description Most recent category refresh time across all stored categories; null when none exist.
             */
            lastRefreshedAt?: string | null;
        };
        RefreshCategoriesResult: {
            /** @description Category records received from UEX. */
            fetched: number;
            /** @description New categories stored this run. */
            inserted: number;
            /** @description Existing categories changed this run. */
            updated: number;
            /** @description Categories present but unchanged this run. */
            unchanged: number;
            /** @description Category records that could not be processed (if any). */
            failed: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** @description Elapsed milliseconds. */
            durationMs: number;
        };
        ImportItemsRequest: {
            /** @description UEX id of the single category to import; omit or null to import all eligible categories. */
            categoryUexId?: number | null;
        };
        CategoryImportError: {
            categoryUexId: number;
            categoryName?: string | null;
            /** @description Human-readable failure reason for this category. */
            message: string;
        };
        ImportItemsResult: {
            /**
             * @description Overall outcome derived from per-category results.
             * @enum {string}
             */
            status: "success" | "completedWithErrors" | "failed";
            categoriesProcessed: number;
            categoriesSucceeded: number;
            categoriesFailed: number;
            /** @description Item records received from UEX across succeeded categories. */
            itemsFetched: number;
            itemsInserted: number;
            /** @description Existing items updated (includes restored */
            itemsUpdated: number;
            /** @description Items present but unchanged this run. */
            itemsUnchanged: number;
            /** @description Records skipped because uuid was null. */
            itemsSkippedNoUuid: number;
            /** @description Items soft-deleted (scoped to imported categories). */
            itemsSoftDeleted: number;
            /** @description Item records that could not be processed individually. */
            itemsFailed: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            durationMs: number;
            /** @description Per-category failures so the admin can retry those categories later. */
            errors: components["schemas"]["CategoryImportError"][];
        };
        /** @description RFC 7807 problem document (as emitted by the API's ProblemDetails middleware). */
        ProblemDetails: {
            title?: string;
            status?: number;
            detail?: string | null;
            instance?: string | null;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacking the Admin role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
