/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/warehouse/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List material inventory (filterable, multi-key sorted).
         * @description Returns material rows sorted by Material name asc, Quality desc, Owner name asc, Location asc. All filters are optional and combine with AND; empty filters are ignored.
         */
        get: operations["getMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/materials/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Selectable Owner and Location options derived from current material inventory. */
        get: operations["getMaterialFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/materials/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search sc.commodities for the add flow (Quartermaster). */
        get: operations["searchMaterialCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/materials/{id}/quantity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set a material row's quantity to a new absolute total (Quartermaster).
         * @description Absolute set — the value is the new total quantity, not a delta. Rounded half-up to 3 decimal places; values <= 0.000 are rejected and the row keeps its prior quantity. Quality, Material, Owner, and Location are never changed.
         */
        put: operations["changeMaterialQuantity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/materials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a material inventory row (Quartermaster). */
        delete: operations["removeMaterial"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/materials#add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a material row, or increment an existing matching row (Quartermaster).
         * @description Real path is POST /api/warehouse/materials (this synthetic path id avoids an OpenAPI path collision with the GET above). Selects a commodity from sc.commodities, assigns owner (defaults to caller), location, quantity (> 0.000), and quality (1..1000, default 500). If a row with the same Material+Owner+Location+Quality exists, its quantity is incremented and 200 is returned; otherwise a new row is created and 201 is returned.
         */
        post: operations["addMaterial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MaterialRowResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            commodityId: string;
            materialName: string;
            materialCode?: string | null;
            /**
             * Format: double
             * @description Decimal with 3 places, > 0.000.
             */
            quantity: number;
            quality: number;
            /** Format: uuid */
            ownerUserId: string;
            ownerDisplayName: string;
            location: string;
        };
        MaterialListResponse: {
            rows: components["schemas"]["MaterialRowResponse"][];
        };
        MaterialFiltersResponse: {
            owners: components["schemas"]["OwnerOption"][];
            locations: string[];
        };
        OwnerOption: {
            /** Format: uuid */
            userId: string;
            displayName: string;
        };
        CommodityCatalogResponse: {
            commodities: components["schemas"]["CommodityCatalogItem"][];
        };
        CommodityCatalogItem: {
            /** Format: uuid */
            commodityId: string;
            name: string;
            code?: string | null;
        };
        AddMaterialRequest: {
            /** Format: uuid */
            commodityId: string;
            /**
             * Format: uuid
             * @description Defaults to the authenticated caller when omitted.
             */
            ownerUserId?: string | null;
            location: string;
            /**
             * Format: double
             * @description > 0.000; rounded half-up to 3 places.
             */
            quantity: number;
            /** @description Defaults to 500 when omitted. */
            quality?: number | null;
        };
        ChangeMaterialQuantityRequest: {
            /**
             * Format: double
             * @description New absolute total; > 0.000, rounded half-up to 3 places.
             */
            quantity: number;
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
        };
    };
    responses: {
        /** @description Not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacks the Quartermaster policy. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Validation failed (e.g. quantity <= 0.000 or quality outside 1..1000). */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMaterials: {
        parameters: {
            query?: {
                /** @description Case-insensitive partial match over commodity name and code. */
                material?: string;
                /** @description Single owner filter. */
                ownerUserId?: string;
                /** @description Single known location filter. */
                location?: string;
                qualityMin?: number;
                qualityMax?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Material inventory list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMaterialFilters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available filter options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialFiltersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchMaterialCatalog: {
        parameters: {
            query?: {
                search?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching commodities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommodityCatalogResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    changeMaterialQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeMaterialQuantityRequest"];
            };
        };
        responses: {
            /** @description Updated row. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRowResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMaterialRequest"];
            };
        };
        responses: {
            /** @description Existing matching row incremented. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRowResponse"];
                };
            };
            /** @description New row created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRowResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Commodity or owner not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
