/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/discord/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin Discord OAuth2 authorization-code flow (browser redirect endpoint).
         * @description BROWSER REDIRECT ENDPOINT — not called via fetch. The SPA points the browser at this URL.
         *     The server issues an OAuth correlation/state cookie and a 302 redirect to Discord's
         *     authorization URL with the minimized scope `identify`. No request body, no JSON response.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Discord's authorization endpoint. */
                302: {
                    headers: {
                        Location?: string;
                        /** @description Short-lived OAuth correlation cookie (opaque; no client-readable secrets). */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/discord/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discord OAuth callback (browser redirect endpoint).
         * @description BROWSER REDIRECT ENDPOINT — Discord redirects the browser here. On success the server:
         *     validates OAuth state/correlation, reads the external login, finds or creates the local
         *     Identity user, links the Discord login (AspNetUserLogins), issues the Identity application
         *     cookie, and 302-redirects to the dashboard root. On failure it 302-redirects to the
         *     frontend auth-error page with a short, non-sensitive `reason`. No tokens, codes, or state
         *     appear in any response visible to client scripts.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Authorization code (consumed server-side only; never returned to the client). */
                    code?: string;
                    /** @description Correlation value validated server-side; never echoed to the client. */
                    state?: string;
                    error?: string;
                    error_description?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description On success: 302 to the frontend dashboard root (`/dashboard`).
                 *     On failure: 302 to `/auth/error?reason=<value>` where `reason` is one of:
                 *       - `oauth_error` — Discord returned an error response (user denied, app misconfigured)
                 *       - `state_mismatch` — OAuth correlation/CSRF validation failed
                 *       - `server_error` — Unexpected internal failure during callback processing
                 *     The `reason` value is a safe, non-sensitive label. No OAuth codes, state values,
                 *     or internal details are included.
                 */
                302: {
                    headers: {
                        Location?: string;
                        /**
                         * @description Sets the HTTP-only Identity application session cookie on success; clears the
                         *     external/correlation cookie. Cookie value is opaque to client scripts.
                         */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session state (canonical signed-in probe).
         * @description ALWAYS returns 200. The body is a discriminated union on `authenticated`. This endpoint is
         *     anonymous-accessible by design: an unauthenticated caller receives `{ authenticated: false }`,
         *     NOT a 401. The SPA uses this as the single source of truth for the auth guard. The response
         *     never contains Discord tokens.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session state (authenticated or not). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign the current user out.
         * @description Clears the Identity application session cookie (and any external cookie). Idempotent —
         *     calling without an active session still returns 204 and is a no-op.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session cleared (or already absent). */
                204: {
                    headers: {
                        /** @description Expired session cookie. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Discriminated union returned by `/api/auth/me`; always 200. */
        SessionState: components["schemas"]["AuthenticatedSession"] | components["schemas"]["AnonymousSession"];
        AuthenticatedSession: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            authenticated: "AuthenticatedSession";
            user: components["schemas"]["CurrentUser"];
        };
        AnonymousSession: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            authenticated: "AnonymousSession";
        };
        CurrentUser: {
            /**
             * Format: uuid
             * @description Local application user id (ApplicationUser.Id).
             */
            id: string;
            /** @description Discord global_name, falling back to username. */
            displayName: string;
            /** @description Discord unique handle. No Discord tokens are ever included. */
            discordUsername: string;
        };
        /** @description RFC 7807 Problem Details for protected ACTION endpoints. Never includes internal details. */
        ProblemDetails: {
            /** Format: uri */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
