/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/warehouse/ship-components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Systems-scoped ship component inventory, filtered and multi-key sorted. */
        get: operations["getShipComponents"];
        put?: never;
        /**
         * Add (or increment) a Systems-item inventory row; lazily fetch + cache UEX attributes.
         * @description Restricts the item to the Systems section (non-Systems → 422). On first add of an item with no
         *     cached attributes, fetches `items_attributes` from UEX and builds the typed projection; a UEX
         *     failure is logged and ignored (row still created, attributes Unknown). Increments an existing
         *     matching (item, owner, location) row, otherwise inserts a new row.
         */
        post: operations["addShipComponent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/ship-components/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Selectable filter options derived from current Ship Component inventory only. */
        get: operations["getShipComponentFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/ship-components/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog search restricted to Systems items, for the add flow (Quartermaster). */
        get: operations["searchSystemsCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/items/{id}/quantity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * (Reused from 011) Replace an inventory row's quantity.
         * @description Defined by `011-warehouse-item-inventory`; reused unchanged for Ship Component rows.
         */
        put: operations["changeShipComponentQuantity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * (Reused from 011) Remove an inventory row; the catalog item is untouched.
         * @description Defined by `011-warehouse-item-inventory`; reused unchanged for Ship Component rows.
         */
        delete: operations["removeShipComponent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ShipComponentRow: {
            /**
             * Format: uuid
             * @description Inventory row id (for edit/delete).
             */
            id: string;
            /** Format: uuid */
            itemId: string;
            /** @description Item/component name. */
            name: string;
            /** @description Item category name. */
            type?: string | null;
            /** @description Derived; null → render "Unknown". */
            class?: string | null;
            /** @description Derived; null → render "Unknown". */
            size?: number | null;
            /** @description Derived; null → render "Unknown". */
            grade?: string | null;
            quantity: number;
            /** Format: uuid */
            ownerUserId: string;
            ownerDisplayName: string;
            location: string;
        };
        ShipComponentListResponse: {
            items: components["schemas"]["ShipComponentRow"][];
        };
        OwnerOption: {
            /** Format: uuid */
            userId: string;
            displayName: string;
        };
        ShipComponentFiltersResponse: {
            types: string[];
            classes: string[];
            sizes: number[];
            grades: string[];
            owners: components["schemas"]["OwnerOption"][];
            locations: string[];
            unknownClass: boolean;
            unknownSize: boolean;
            unknownGrade: boolean;
        };
        SystemsCatalogItem: {
            /** Format: uuid */
            itemId: string;
            name: string;
            /** @description Item category name. */
            type?: string | null;
        };
        SystemsCatalogResponse: {
            items: components["schemas"]["SystemsCatalogItem"][];
        };
        AddShipComponentRequest: {
            /**
             * Format: uuid
             * @description Must reference an Active Systems item.
             */
            itemId: string;
            /**
             * Format: uuid
             * @description Defaults to the caller.
             */
            ownerUserId?: string | null;
            /** @description Required; trimmed server-side; rejected when empty. */
            location: string;
            quantity: number;
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacks the Quartermaster/Admin role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getShipComponents: {
        parameters: {
            query?: {
                /** @description Partial item name */
                name?: string;
                /** @description Item category (Type). Repeatable → OR. */
                type?: string[];
                /** @description Component class. Repeatable → OR. */
                class?: string[];
                /** @description Component size. Repeatable → OR. */
                size?: number[];
                /** @description Component grade. Repeatable → OR. */
                grade?: string[];
                /** @description Owner. Repeatable → OR. */
                ownerUserId?: string[];
                /** @description Location. Repeatable → OR. */
                location?: string[];
                /** @description Include rows whose Class is Unknown (null) */
                unknownClass?: boolean;
                /** @description Include rows whose Size is Unknown (null). */
                unknownSize?: boolean;
                /** @description Include rows whose Grade is Unknown (null). */
                unknownGrade?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered, sorted Systems-scoped inventory list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipComponentListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addShipComponent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddShipComponentRequest"];
            };
        };
        responses: {
            /** @description Existing row incremented. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipComponentRow"];
                };
            };
            /** @description Row created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipComponentRow"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Item or owner not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Item is not in the Systems section (not addable from Ship Components). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getShipComponentFilters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filter option lists and Unknown availability flags. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipComponentFiltersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchSystemsCatalog: {
        parameters: {
            query?: {
                /** @description Partial item name */
                search?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching Systems catalog items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemsCatalogResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    changeShipComponentQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Updated row. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipComponentRow"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Inventory row not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    removeShipComponent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Inventory row not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
