/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/ships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List imported ship records (paginated).
         * @description Returns a page of imported ships ordered by name. Includes both active and soft-deleted records;
         *     `status` distinguishes them (FR-010). Drives the data table (FR-006) and the empty state (FR-007).
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page number. */
                    page?: number;
                    /** @description Records per page (default 25). */
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of ship records (possibly empty). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedShips"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the full record for a single ship.
         * @description Returns the complete, verbatim set of feed fields for one ship (all 64 fields) plus its status,
         *     powering the right-side detail sheet (FR-008, US3). Fields with no value are present and empty so
         *     the full data shape is visible.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ship's local surrogate id (not the UEX id). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The ship's full detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShipDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description No ship with that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ships/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a ship data import from the UEX feed.
         * @description Fetches the full UEX vehicle feed server-side and performs a transactional upsert: inserts new
         *     ships, updates existing ones, reactivates previously soft-deleted ships that reappear (FR-011),
         *     and soft-deletes ships absent from the feed (FR-009). All-or-nothing: any failure rolls back and
         *     leaves stored data unchanged (FR-005). If the feed returns zero records, no changes are made and
         *     a warning is returned. Only one import may run at a time (FR-003).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Import completed; counts of what changed (FR-004). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
                /**
                 * @description Feed returned zero records — no changes applied (edge case). Body carries a warning message and
                 *     zeroed counts.
                 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description An import is already in progress (FR-003). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description The external UEX feed was unavailable or returned an unusable response (FR-005); no changes applied. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session probe (extended with roles).
         * @description Documented here only for the additive `roles` field this feature adds to the authenticated
         *     response. Always returns 200 (session probe never 401s). See the 002 auth contract for the full
         *     definition; the authenticated payload gains `user.roles: string[]`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current session state, including roles when authenticated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticatedSessionWithRoles"] | components["schemas"]["AnonymousSession"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description active = present in the latest feed (or reactivated); softDeleted = absent from the latest feed.
         * @enum {string}
         */
        ShipStatus: "active" | "softDeleted";
        ShipListItem: {
            /**
             * Format: uuid
             * @description Local surrogate id.
             */
            id: string;
            /** @example 100i */
            name: string;
            /** @example Origin Jumpworks */
            companyName?: string | null;
            status: components["schemas"]["ShipStatus"];
        };
        PagedShips: {
            items: components["schemas"]["ShipListItem"][];
            /** @example 1 */
            page: number;
            /** @example 25 */
            pageSize: number;
            /** @example 278 */
            totalCount: number;
            /** @example 12 */
            totalPages: number;
        };
        ShipDetail: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ShipStatus"];
            /**
             * @description Verbatim map of all feed fields for the ship (all 64 keys from the UEX record), stored as-is
             *     (e.g. is_* flags as 0/1, dates as unix timestamps, some numbers as strings). Rendered read-only
             *     in the detail sheet; empty values are present and shown explicitly.
             */
            fields: {
                [key: string]: unknown;
            };
        };
        ImportResult: {
            /** @description New ships inserted this run. */
            added: number;
            /** @description Existing active ships refreshed this run. */
            updated: number;
            /** @description Previously soft-deleted ships brought back (FR-011). */
            reactivated: number;
            /** @description Ships absent from the feed */
            softDeleted: number;
            /** @description Total ship records active after the run / records in the feed. */
            total: number;
            /** @description Set when the feed returned zero records and no changes were applied. */
            warning?: string | null;
        };
        /**
         * @description Role names held by the signed-in user; drives admin UI gating.
         * @example [
         *       "Admin"
         *     ]
         */
        SessionRoles: string[];
        AuthenticatedSessionWithRoles: {
            /** @enum {boolean} */
            authenticated: true;
            user: {
                /** Format: uuid */
                id: string;
                displayName: string;
                discordUsername: string;
                roles: components["schemas"]["SessionRoles"];
            };
        };
        AnonymousSession: {
            /** @enum {boolean} */
            authenticated: false;
        };
        /** @description RFC 7807 problem document (as emitted by the API's ProblemDetails middleware). */
        ProblemDetails: {
            title?: string;
            status?: number;
            detail?: string | null;
            instance?: string | null;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacking the Admin role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
