/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/warehouse/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inventory (any authenticated user), filtered and sorted by Name ascending. */
        get: operations["getInventory"];
        put?: never;
        /** Add a catalog item to inventory, or increment the quantity of a matching row. Quartermaster only. */
        post: operations["addInventoryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/items/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distinct Type/Subtype (from item-category data) and Owner options for filter controls. Any authenticated user. */
        get: operations["getInventoryFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/items/{id}/quantity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the quantity of an inventory row. Quartermaster only. */
        put: operations["changeInventoryQuantity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an inventory row. The catalog item is unaffected. Quartermaster only. */
        delete: operations["removeInventoryItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the active item catalog by name for the add flow. Quartermaster only. */
        get: operations["searchCatalogItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InventoryListResponse: {
            items: components["schemas"]["InventoryRow"][];
        };
        InventoryRow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            itemId: string;
            name: string;
            /** @description Item Section. */
            type?: string | null;
            /** @description Item Category. */
            subtype?: string | null;
            quantity: number;
            /** Format: uuid */
            ownerUserId: string;
            ownerDisplayName: string;
            location: string;
        };
        InventoryFiltersResponse: {
            types: string[];
            subtypes: string[];
            owners: components["schemas"]["OwnerOption"][];
        };
        OwnerOption: {
            /** Format: uuid */
            userId: string;
            displayName: string;
        };
        CatalogItem: {
            /** Format: uuid */
            itemId: string;
            name: string;
            type?: string | null;
            subtype?: string | null;
        };
        AddInventoryItemRequest: {
            /** Format: uuid */
            itemId: string;
            /** @description Amount to add (incremented onto an existing matching row). */
            quantity: number;
            /** @description Trimmed server-side; rejected if empty after trim. */
            location: string;
            /**
             * Format: uuid
             * @description Owner; defaults to the authenticated caller when omitted (FR-011).
             */
            ownerUserId?: string | null;
        };
        ChangeQuantityRequest: {
            /** @description Replacement value (not additive). */
            quantity: number;
        };
        Problem: {
            title?: string;
            detail?: string;
            status?: number;
        };
    };
    responses: {
        /** @description No authenticated session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but lacks the Quartermaster/Admin role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Request failed validation (e.g. quantity < 1, empty location). */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInventory: {
        parameters: {
            query?: {
                /** @description Partial item name */
                name?: string;
                /** @description Exact Type (item Section). */
                type?: string;
                /** @description Exact Subtype (item Category). */
                subtype?: string;
                /** @description Exact owner. */
                ownerUserId?: string;
                /** @description Partial location */
                location?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered inventory list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addInventoryItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddInventoryItemRequest"];
            };
        };
        responses: {
            /** @description Existing row incremented. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryRow"];
                };
            };
            /** @description New row created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryRow"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Referenced catalog item or owner does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getInventoryFilters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available filter option values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryFiltersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changeInventoryQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeQuantityRequest"];
            };
        };
        responses: {
            /** @description Quantity updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryRow"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No inventory row with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeInventoryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Row removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No inventory row with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    searchCatalogItems: {
        parameters: {
            query?: {
                /** @description Partial item name */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching catalog items (capped). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
